#!/bin/bash
opcao=1
while [ $opcao != '0' ]
do
echo " "
echo " ==================================================== "
echo " _____ _ _       _                  _____ _   _ _     "
echo "/  __ \ (_)     (_)                |_   _| | | | |    "
echo "| /  \/ |_ _ __  _  __ _   ______    | | | | | | |    "
echo "| |   | | |  _ \| |/ _  | |______|   | | | | | | |    "
echo "| \__/\ | | | | | | (_| |           _| |_| |_| | |____"
echo " \____/_|_|_| |_|_|\__  |           \___/ \___/\_____/"
echo "                      | |                             "
echo "                      |_|                             "
echo " ==================================================== "
echo " "
echo "Selecione a opção pretendia: "
echo " "
echo " 1 - Criar paciente"
echo " 2 - Criar Médico "
echo " 3 - Stats"
echo " 4 - Avaliar médicos"
echo " 0 - Sair"
read opcao
case $opcao in
'1')
./cria_pacientes.sh ;;
'2')
echo "Nome"
read nome
echo "Numero"
read numero
echo "Especialidade"
read especialidade
echo "E-mail"
read email
./cria_medico.sh $nome $numero $especialidade $email ;;
'3')
echo "Insira a Localidade a pesquisar"
read localidade
echo "Insira o valor a pesquisar"
read valor
sudo ./stats.sh $localidade $valor ;;
'4')
./avalia_medicos.sh  ;;
'0')
;;
?)
echo " Valor invalido" ;;
esac
done

